[project]
name = "InterviewPreparationWithAI"
version = "0.0.1"
description = ""
authors = [{ name="Oleg Reva", email = "virtualmaestro@gmail.com"}]

dependencies = [
    "streamlit >= 1.49.1"
]

requires-python = ">=3.11"

